POST http://localhost:4000/user/register
Content-Type: application/json

{
    "name": "foo3",
    "email": "bar4@gmail.com",
    "password": "1234abcd"
}

###
GET http://localhost:4000/user/email=foobar@gmail.com
